[book]
authors = ["jmarcelomb"]
language = "en"
multilingual = false
src = "src"
title = "Marcelo's Wiki"

[output.html]
default-theme = "macchiato"
preferred-dark-theme = "macchiato"
additional-css = [
  "./theme/catppuccin.css",
  "./theme/catppuccin-admonish.css",
  "./theme/catppuccin-alerts.css",
]
no-section-label = true
git-repository-url = "https://github.com/jmarcelomb/wiki"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/jmarcelomb/wiki/edit/master/{path}"
cname = "wiki.marceloborges.dev"
